# -*- coding: utf-8 -*-
"""a10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11bXPjwYAMzyF98_PXyT6ajYJkzYdDwRE

# Market dynamics: A journey through sales from city to city
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import plotly.express as px
from sklearn.linear_model import LinearRegression

path= "https://raw.githubusercontent.com/andreafloresk/Basa-de-datos/main/dataset_visualizacion_datos.csv"
df=pd.read_csv(path)
df.head(6)

"""* The dataset "Market dynamics: A journey through sales from city to city" is a synthetic compilation designed to simulate sales transactions across different cities and product categories, intended for educational purposes in data visualization and analysis.
* The dataset is artificially generated to mimic real-world sales data, ensuring a variety of scenarios for analysis. It does not come from an external data source but is created to facilitate learning and practice in data visualization techniques.

**Variable names and types**
* Fecha: Numerical (Continuous) - Represents the date of each transaction.
* Categoría: Categorical - Specifies the product category for each sale.
* Cantidad Vendida: Numerical (Discrete) - Indicates the number of units sold in each transaction.
* Precio por Unidad: Numerical (Continuous) - Lists the sale price for each unit in a transaction.
* Ciudad: Categorical - Identifies the city where each transaction took place.
"""

df.columns

"""
**Which city has the highest average sales quantity, and how does this compare to the city with the lowest average sales quantity?**



"""

pivot_table = df.pivot_table(values='Cantidad Vendida', index='Ciudad', aggfunc='mean')
pivot_table = pivot_table.round(2)
pivot_table.columns = ['Average Sales Quantity']
print(pivot_table)

"""There is a variation in the average sales quantity among the cities. Ciudad C has the highest average sales quantity at 10.41, which suggests that either the demand for products in Ciudad C is higher than in the other cities, or that the sales strategies in place are more effective.Cities with lower average sales quantities, like Ciudad A, might be identified as areas where sales strategies could be improved, or where additional marketing, promotions, or stock could be considered to increase sales.

**How do sales volumes compare across different product categories?**
"""

plt.figure(figsize=(10, 6))
category_order = df['Categoría'].value_counts().index
sns.countplot(data=df, x='Categoría', order=category_order)
plt.title('Sales Count by Product Category')
plt.xlabel('Category')
plt.ylabel('Count')

"""The bar chart titled "Sales Count by Product Category" illustrates the distribution of sales across five different product categories. From this visualization, we can conclude the following:
* The 'Electrónicos' category has the highest number of sales, making it the most popular or most frequently purchased category among the ones listed.
* The 'Juguetes' category follows closely behind, indicating it is also a popular choice among consumers. The categories 'Alimentos' and 'Ropa' show a moderate number of sales, while the 'Libros'category has the lowest count, suggesting it is the least popular in terms of the number of sales transactions during the period observed.
* The data could inform inventory decisions, indicating the need to stock more electronic items and toys compared to books, food, or clothing.

**What are the trends in monthly sales, and can you identify any seasonality or significant changes in sales volume over time?**
"""

df['Fecha'] = pd.to_datetime(df['Fecha'])
df['Month'] = df['Fecha'].dt.to_period('M')

df_monthly = df.groupby('Month').agg({'Cantidad Vendida':'sum'}).reset_index()
df_monthly['Month'] = df_monthly['Month'].astype(str)

pivot_table = df_monthly.pivot_table(values='Cantidad Vendida', index='Month', aggfunc='sum')
pivot_table.columns = ["Total Sales Quantity Over Time"]
print(pivot_table)

plt.figure(figsize=(12, 6))
sns.lineplot(data=df_monthly, x='Month', y='Cantidad Vendida')
plt.title('Total Sales Quantity Over Month')
plt.xlabel('Month')
plt.ylabel('Total Sales Quantity')
plt.xticks(rotation=45)

"""The line plot demonstrates a consistent upward trend in total sales quantity over the given three-month period. Starting from January, there is a clear increase in sales each subsequent month through to March. This could indicate a successful period for the business with increasing customer demand, effective sales strategies, or seasonal factors that are positively impacting sales.

**How does the sales distribution vary across different cities, and which city shows the greatest variability in sales?**
"""

plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Ciudad', y='Cantidad Vendida')
plt.title('Sales Quantity Distribution by City')
plt.xlabel('City')
plt.ylabel('Sales Quantity')
plt.tight_layout()

"""* Central Tendency: The median sales quantity, indicated by the horizontal line in the middle of each box, varies slightly among the cities. Ciudad C appears to have a higher median sales quantity compared to Ciudad A and Ciudad B.
* Variability: The interquartile range (IQR), represented by the height of each box, shows how sales quantities are spread around the median. Ciudad B shows a tighter IQR compared to the other two cities, indicating less variability in sales quantity.
* Range: The vertical lines (whiskers) extending from the boxes indicate the overall range of the sales data, excluding outliers. Ciudad C has the widest range, suggesting more variation in the sales quantity.

**How is the total quantity of products sold distributed among the different cities represented in the data?**
"""

MarketShare = df.groupby('Ciudad')['Cantidad Vendida'].sum()
MarketShare.plot(kind='pie', autopct='%1.1f%%', startangle=140, figsize=(8, 8))
plt.title('Market Share by City')
plt.ylabel('')
plt.show()

"""Ciudad C has the largest market share with 42.2% of the total product quantities sold, followed by Ciudad B with 35.1%. Ciudad A has the smallest share at 22.7%. This indicates that Ciudad C is the leading city in terms of sales volume, which could be due to various factors such as larger customer base, more aggressive marketing, or a wider range of products.

**How does the total sales volume distribute among different cities, within each product category?**
"""

df_summed = df.groupby(['Ciudad', 'Categoría'])['Cantidad Vendida'].sum().reset_index()
fig = px.sunburst(df_summed, path=['Ciudad', 'Categoría'], values='Cantidad Vendida', color='Ciudad',
                  title='Sales Volume Distribution Among Cities and Product Categories')

fig.show()

"""- Ciudad C dominates the sales, particularly in the 'Electrónicos' category.
- Ciudad A and Ciudad B also show significant sales in 'Electrónicos' and 'Juguetes'.
- Categories like 'Libros' and 'Ropa' have a more even distribution across the cities, though still with a noticeable concentration in Ciudad C.
- Ciudad A seems to have a comparative advantage in 'Juguetes'.

**How does the quantity of products sold relate to the unit price across all transactions? Is there a negative or positive correlation between quantity sold and unit price?**
"""

X = df['Precio por Unidad'].values.reshape(-1,1)
y = df['Cantidad Vendida'].values

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['Precio por Unidad'], y=df['Cantidad Vendida'])
sns.lineplot(x=df['Precio por Unidad'], y=y_pred, color='red')

plt.title('Relationship Between Unit Price and Quantity Sold')
plt.xlabel('Unit Price')
plt.ylabel('Quantity Sold')

plt.show()

"""- **Cantidad vendida=b1(Precio por unidad)+b0**
- **Cantidad vendida= 0.033(Precio por unidad) + 7.749311**
- The coefficient (slope) is positive (approximately 0.033), indicating that, on average, as the unit price increases, the quantity sold also increases slightly. This could suggest that for this particular dataset, higher prices do not deter customers from purchasing the products, or it could indicate that more expensive items are sold in larger quantities. The intercept is approximately 7.749, indicating the expected quantity sold when the unit price is zero.

**What is the distribution of unit prices across all products? Do most products fall within a certain price range?**
"""

plt.figure(figsize=(10, 6))
plt.hist(df['Precio por Unidad'], bins=20, color='skyblue', edgecolor='black')

plt.title('Distribution of Unit Prices')
plt.xlabel('Unit Price')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

"""The histogram of unit prices suggests that the distribution of prices is relatively even across the spectrum, without a single dominant price range. Most products are distributed across various price points, with a moderate concentration of products in the 40-60 unit price range."""